name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make test_grid
      run: make test_grid
    - name: Lancer les tests
      run: ./tests/test_grid
    - name: make test_wator
      run: make test_wator
    - name: Lancer les tests de wator
      run: ./tests/test_wator
